### ISSUE TITLE
Окна не двигаются вверх, но при одном условии

### ISSUE THREAD

**Issue by IteratorW** [IgorTimofeev/GUI#10]
Приветствую, сам баг довольно таки минорен, но баг есть баг.
Если нажатие по окну произойдет в районе его первой линии, то оно не будет двигаться вверх, вообще. Только в другие стороны. Если нажатие будет ниже, то все будет двигаться.
Код - из примера окошек в readme.
На скриншоте выделенная область как раз таки то, о чем я говорил.
![image](https://user-images.githubusercontent.com/30198566/50780222-6ede0200-12b3-11e9-80a0-5f7d8b352a89.png)

**Comment by IgorTimofeev** [comment]
@IteratorW, экранные сигналы в опенкомпах разграничиваются попиксельно, а верхняя полоска имеет размер как раз в один псевдографический пиксель. В реальной ОС аналогичная полоска в один пиксель не привела бы к перемещению окна, мяу. Так с чего бы должна приводить тут?
