### ISSUE TITLE
Some objects are not drawed

### ISSUE THREAD

**Issue by PizzaAddict** [IgorTimofeev/GUI#12]
[src.zip](https://github.com/IgorTimofeev/GUI/files/3316753/src.zip)
I've uploaded code file directly. unzip, copy the code into the clipboard, then run screen.lua on opencomputer.

at first, everything seems working fine. but when I change size of the table by typing some number in the inputbox, some of the rows are beginning to be omitted on the screen.
I've checked my code many times, but couldn't find any problem. maybe the GUI lib has some issues?

**Comment by IgorTimofeev** [comment]
This library is no longer supported, since it became part of the MineOS about six months ago. If it has some issues - I don't care cause it exists only as \*compatibility\* thing

(too lazy to download, copy, run minecraft and brrrrr)
