### ISSUE TITLE
PIC problems

### ISSUE THREAD

**Issue by schloops1** [IgorTimofeev/GUI#13]
Hi, I'm using your great GUI library for a project that is nearing readiness to be released but it's suffering from having "?" instead of graphics for a bunch of controls such as switches and so on.
I'm using your library (last release) on MC 1.12.2 and OpenComputers 1.74 (and something).
Any idea what is going on?
Have a nice day!

**Comment by IgorTimofeev** [comment]
Hm, seems interesting. By "?" do you mean missing characters? I.e. everything is normal, but letters doesn't display? Or what?

**Comment by IgorTimofeev** [comment]
Meow, for some reason these chars are not supported by your OpenComputers mod verision. Nothing I can do here
