### ISSUE TITLE
Color palette crash.

### ISSUE THREAD

**Issue by raymondbh** [IgorTimofeev/GUI#14]
Tried to use the color palette in a GUI i am programming but it just crashes. Tried to copy your example, but that crashes too:
![image](https://user-images.githubusercontent.com/4389846/70392586-cc0d9680-19e1-11ea-842a-779b162a944b.png)
Crashes the second I click a color in the palette.

**Comment by raymondbh** [comment]
Seems like this is only a problem on the OpenComputerVM... so not that important then... :)

**Comment by IgorTimofeev** [comment]
Anyway libray is NOT supported. Any crashes may be fixed only on MineOS repo
