### ISSUE TITLE
listAddItem is broken

### ISSUE THREAD

**Issue by ShadowEO** [IgorTimofeev/GUI#7]
Attempting to add multiple items to a list ends with only one item being added and subsequent requests being ignored.

Current Behavior:
Using a program with the following:
`listObj:addItem("Test")
listObj:addItem("Test 2")
`
Results in a single item listbox, the Test 2 item never appears and is not touchable.

Expected Behavior:
Both items appear in list box as designed.

**Comment by ShadowEO** [comment]
I retract my previous statement, it is working correctly. Not sure what I did wrong the first time, but after rewriting the line almost exactly like the demo, the other items appeared....

**Comment by IgorTimofeev** [comment]
meow <3
