### ISSUE TITLE
Слайдер выдаёт в value неведомую хрень

### ISSUE THREAD

**Issue by BTVoidX** [IgorTimofeev/GUI#8]
При изменении слайдера он должен вывести своё новое значение на экран.
Он же выводит это:
![default](https://user-images.githubusercontent.com/37330718/50421475-40930800-0859-11e9-8168-0948fb03b4dc.png)
Причём этот текст не меняется в зависимости от числа на слайдере.

Код:
(Взято из документации по GUI)
```
local slider = mainContainer:addChild(GUI.slider(4, 2, 30, 0x66DB80, 0x0, 0xFFFFFF, 0xAAAAAA, 0, 100, 50, true, "Prefix: ", " postfix"))
slider.roundValues = true
slider.onValueChanged = function(value)
  print(value)
end
```

**Comment by IgorTimofeev** [comment]
@BTVoidX Зараза, опять документация не обновлена. Ща исправлю, спасибо. На самом деле в метод onValueChanged передается ссылка на главный контейнер, затем на объект, а затем уже на данные события по местному "стандарту":

![2018-12-25 16 07 57](https://user-images.githubusercontent.com/11760002/50422847-42f86080-085f-11e9-857a-a3a0509487c2.png)

Так что для получения value по коду выше юзай object.value, либо, если обращаться к твоему примеру, slider.value.
